### ISSUE TITLE
File descriptors leak

### ISSUE THREAD

**Issue by mguijarr** [tango-controls/pytango#324] opened 2019-12-23 15:28 UTC
Hi,

`DeviceProxy` objects leave open file descriptors, even if the object is destroyed.

Here is a small snippet to get evidence of the problem (needs **psutil** Pyhon module):

```python
import tango
import psutil

current_process = psutil.Process()

prev_fds = current_process.num_fds()

print("Connecting to a device server")

dev_proxy = tango.DeviceProxy("id00/simulator/simulator1")

print("  xxx destroying device proxy xxx")

del dev_proxy

print(f"{current_process.num_fds()-prev_fds} file descriptors left open.")

print("Connecting to another device server")

dev_proxy = tango.DeviceProxy("id00/simulator/simulator2")

print("  xxx destroying device proxy xxx")

del dev_proxy

print(f"{current_process.num_fds()-prev_fds} file descriptors left open.")

print("Reconnecting to the same first device server")

dev_proxy = tango.DeviceProxy("id00/simulator/simulator1")

print("  xxx destroying device proxy xxx")

del dev_proxy

print(f"Still {current_process.num_fds()-prev_fds} file descriptors left open.")

input("Restart the first server, and press Enter to continue")

dev_proxy = tango.DeviceProxy("id00/simulator/simulator1")

print("  xxx destroying device proxy xxx")

del dev_proxy

print(f"{current_process.num_fds()-prev_fds} file descriptors left open.")
```

It shows 1 file descriptor leaks in all cases, then there is an additional file descriptor left open per `DeviceProxy` object. Reconnecting to a previous device server does not increase the number of opened file descriptors. However, if the server is restarted a new `DeviceProxy` will take a new file descriptor.

This is really problematic for automatic test pipelines, for example : if there are 1000+ tests, and tests often start/stop device servers, the system reaches the file descriptors limit at some point...

**Comment by andygotz** [comment] 2020-01-06 16:18
@mguijarr thanks for the bug report. I wonder if there is some cleanup routine which could be called and which is not being called. @bourtemb, @mliszcz do you have any idea how the file descriptor being left open can be prevented?

@mguijarr is this a problem only when running the tests or does it occur under operating conditions as well i.e. do you create and delete to device servers many times ?

**Comment by bourtemb** [comment] 2020-01-06 16:54
I think this is due to the way omniORB is handling the connections.
If you wait long enough, the file descriptors are actually closed. I confirmed that by adding some 
`input("Press enter to continue")`
lines in the provided example and by monitoring the number of open file descriptors with 
`watch -n 1 ls -l /proc/<pid>/fd`
I have been playing with a simple pure omniORB small program which is doing something similar as what happens when we delete a DeviceProxy object and I observe the same behaviour.
When the CORBA object is released, the file descriptor is still open for a while.
And if we try to create another CORBA object referencing the same object again, CORBA seems to reuse the previously and still open file descriptor.
One suggestion from @taurel is to call `tango.ApiUtil.cleanup()` to force the cleanup of all the CORBA connections (and destroy the ORB!) in your use case if relevant. Be careful because any CORBA object created before the cleanup will no longer be valid so it might not fit your use case.
The PyTango doc gives another use case where `tango.ApiUtil.cleanup()` could be useful: https://pytango.readthedocs.io/en/stable/howto.html#using-clients-with-multiprocessing
It might be useful for your use case @mguijarr since you are encountering this issue while executing some tests.

There is a bunch of omniORB parameters which can also be used to tune the omniORB behaviour, there might be some parameters which can be tuned to get the behaviour you are expecting...
I will now have a deeper look into that.

**Comment by bourtemb** [comment] 2020-01-06 17:37
> I have been playing with a simple pure omniORB small program which is doing something similar as what happens when we delete a DeviceProxy object and I observe the same behaviour.
> When the CORBA object is released, the file descriptor is still open for a while.
> And if we try to create another CORBA object referencing the same object again, CORBA seems to reuse the previously and still open file descriptor.

omniORB also reuses the already open connection if the program tries to access to another CORBA object managed by the same server.

You can play with `outConScanPeriod` omniORB parameter (default = 120 s), which is described in these sections of the omniORB documentation:
http://omniorb.sourceforge.net/omni42/omniORB/omniORB004.html#sec62
http://omniorb.sourceforge.net/omni42/omniORB/omniORB006.html#sec%3AconnShutdown

I made a small test reducing  `outConScanPeriod` to 15 seconds and indeed, it cleans up the connections much faster.
I think you can set ORBoutConScanPeriod environment variable to the value you want (must be a multiple of `scanGranularity ` ORB parameter (5 s by default)) and test different values of this parameter. This might help you solving your issue too.

**Comment by mguijarr** [comment] 2020-01-07 12:16
@andygotz this is a problem for the tests only

I confirm the workaround proposed by @taurel and @bourtemb (i.e to call `ApiUtil.cleanup()`) cleans the file descriptors when using normal Tango `DeviceProxy`.

When using Tango with gevent ("green" version), there are 2 more file descriptors left open. I guess this is due to the gevent threadpool. But this number of file descriptors do not increase as servers are restarted, so it is much less serious.

**Comment by andygotz** [comment] 2020-01-07 20:49
@mguijarr sounds good. If you agree can you close the issue? Thanks!

**Comment by ajoubertza** [comment] 2020-02-03 20:30
No activity on this issue, so closing it.

**Closed as completed by ajoubertza** 2020-02-03 20:30 UTC
