### ISSUE TITLE
Concurrent event channel subscriptions

### ISSUE THREAD

**Issue by AntoineDupre** [tango-controls/pytango#307] opened 2019-09-20 16:33 UTC
Hi,

I notice that the tango event subscription on the client seems to not be thread safe. Two concurrent subscriptions (on whatever device/attribute) generate after 10 seconds two errors from the heartbeat:
```
errors = (DevError(desc = 'Event channel is not responding anymore, maybe the server or event system is down', origin = 'EventConsumer::KeepAliveThread()', reason = 'API_EventTimeout', severity = tango._tango.ErrSeverity.ERR),)
```
The following example can trigger this problem:
```python
import tango
from threading import Thread
from functools import partial
from time import sleep


def cb(e):
    """ Tango event callback"""
    if e.err:
        print(e)


def subscribe_event(ds, attr):
    """ Periodic event subscription """
    ds.subscribe_event(attr, tango.EventType.PERIODIC_EVENT, cb)


# Create proxy
ds = tango.DeviceProxy("sys/tg_test/1")
attrs = "double_scalar", "boolean_scalar"

# Enable tango polling to get periodic events
for attr in attrs:
    ds.poll_attribute(attr, 1000)

# Prepare threads
threads = [Thread(target=partial(subscribe_event, ds, attr)) for attr in attrs]

# Subscribe
for th in threads:
    th.start()

# Wait for heartbeat and error to popup
print("Waiting for heart beat ....")
for i in range(10):
    print("Heartbeat in {} sec".format(10 - i))
    sleep(1)

sleep(5)
```
It is also failing with Asyncio green mode (delegate subscription to a task instead to a thread)
I did not try with Gevent.
A simple `sleep(0.1)` between subscription fix the issue.

I managed to reproduce this problem by subscribing to two events channel with the following setup:
 * two different tango devices running on two different tango servers (two different dserver)
 * two different tango devices on the same server
 * two different attributes on the same server
 * subscribe two times to the same attribute

I suspect the problem to be on the C++ layer but I did not try with a C++ client.

Is it a known issue ? Can someone tries to reproduce this error ?

Thanks,

**Comment by tiagocoutinho** [comment] 2019-11-22 12:40
Hi @AntoineDupre,

I can reproduce the problem with PERIODIC_EVENT and CHANGE_EVENT.
(tested with python 3.7 and PyTango 9.2.5 and libtango 9.2.5)

I also suspected this is coming from the tango C++ layer so I wrote a simple C++ client and I think I can reproduce the problem.
I attached it [here](https://github.com/tango-controls/pytango/files/3879504/test_dev_sub.cpp.tar.gz)

to compile it:
```console
$ c++ -o test_dev_sub test_dev_sub.cpp -ltango -lomniORB4 -lomnithread -lpthread
```

Before I move it to the tango C++ list, could you confirm that you can also reproduce it?
Thanks

**Comment by bourtemb** [comment] 2019-11-22 12:57
Hi @tiagocoutinho,
Thanks for the C++ example.
I tried it and the reason why it is not working is because it is using standard threads without using an omni_thread::ensure_self object.
The subscription is thread safe, but only if you are using omnithreads or using ensure_self objects during the life time of your threads.

If you apply the following patch it will work:

```
--- test_dev_sub.cpp	2019-11-22 13:54:36.189755000 +0100
+++ test_dev_sub-fixed.cpp	2019-11-22 13:54:25.931841000 +0100
@@ -25,6 +25,7 @@
 
 void subscribe(DeviceProxy &d, int index, CB &cb)
 {
+  omni_thread::ensure_self es;
   try {
     d.subscribe_event(attrs[index], PERIODIC_EVENT, &cb);
   }
```

**Comment by AntoineDupre** [comment] 2019-11-25 17:18
Hi @tiagocoutinho , @bourtemb 

Thanks for the answers, `omni_thread::ensure_self es;` fixes this issue.
Does it makes sense to had this in the boost layer
```
+++ b/ext/device_proxy.cpp
@@ -579,7 +579,7 @@ namespace PyDeviceProxy
         if (bopy::extract<PyCallBackPushEvent&>(py_cb).check()) {
             cb = bopy::extract<PyCallBackPushEvent*>(py_cb);
             cb->set_device(py_self);
-
+            omni_thread::ensure_self es;
             AutoPythonAllowThreads guard;
             return self.subscribe_event(event, cb, stateless);
         }
@@ -604,11 +604,12 @@ namespace PyDeviceProxy
 
             cb->set_device(py_self);
             cb->set_extract_as(extract_as);
-
+            omni_thread::ensure_self es;
             AutoPythonAllowThreads guard;
             return self.subscribe_event(attr_name, event, cb, *filters, stateless);
         } else {
             event_queue_size = bopy::extract<int>(py_cb_or_queuesize);
+            omni_thread::ensure_self es;
             AutoPythonAllowThreads guard;
             return self.subscribe_event(attr_name, event, event_queue_size,
                                         *filters, stateless);
```

I tried this patch with PyTango unittest, with my example and with asyncio green mode (delegate subscription with python threads).

Can adding this `omni_thread::ensure_self es;` directly into boost can introduced some unpected behavior ? (i noticed that it is already present in few places in PyTango boost).

/Antoine

**Comment by ajoubertza** [comment] 2019-11-26 20:21
> I agree it will be nice to include something like this automatically in PyTango so that user don't have to worry.  

I agree it will be nice to include something like this automatically in PyTango so that user doesn't have to worry.  One option is add it to the `AutoPythonAllowThreads` no GIL "guard" class we are using.  It seems to be used wherever we are doing network I/O (at least that is what the comment suggests), so included in DeviceProxy, DeviceAttribute,  Groups, and server initialisation.

Another option is expose ensure_self via Boost, and then to make an a new Python class deriving from `threading.Thread` that uses it.  The downside of this approach is that users have to know they must use this special class for their own threads.

> Can adding this `omni_thread::ensure_self es;` directly into boost can introduced some unpected behavior ? (i noticed that it is already present in few places in PyTango boost).

Good question.  Hopefully...  

For some more background on this issue, I found this [old sourceforge post](https://sourceforge.net/p/tango-cs/bugs/833/). 
And some omnithread [documentation](https://fossies.org/dox/omniORB-4.2.3/classomni__thread_1_1ensure__self.html).

**Comment by tiagocoutinho** [comment] 2019-11-28 08:57
Tango C++ is supposed to be thread safe. There is no mention to `ensure_self` whatsoever in the Tango C++ documentation, so we don't know which calls to the Tango C++ layer need to be protected with `ensure_self`. 

IMHO, Tango C++ should protect itself with `ensure_self` where it needs. Another benefit would be that any other library (ex: qtango) would profit from this improvement.

If not, then I propose the Tango c++ documents which calls need to have this protection so that in PyTango we know what code needs to be changed.

**Comment by ajoubertza** [comment] 2019-11-28 20:12
@tiagocoutinho I agree it would be ideal if cppTango could protect us.

I tried adding `ensure_self` to the `AutoPythonAllowThreads` class and it solves the problem in this issue, and also #292.    The unit tests still pass as well.

I don't know if instantiating `ensure_self` multiple times in the same thread would be a problem, nor if there will be a problem if we instantiate it in a thread that is already an omnithread.  Maybe the C++ experts can comment?

If adding an extra `ensure_self` doesn't hurt, and makes PyTango more robust, then it seems like a reasonable solution.  It is may also be a quicker way to get the fix to users, rather than requiring a new cppTango update.

I'll make a draft PR in the meantime.

**Comment by tiagocoutinho** [comment] 2019-11-29 06:45
> I don't know if instantiating ensure_self multiple times in the same thread would be a problem, nor if there will be a problem if we instantiate it in a thread that is already an omnithread. 

Not an omniORB expert but I have the same opinion

I just thought I should mention that I think the proper place to fix this issue is the Tango C++ layer. If we can have a quick fix here I am not against it. At ALBA we are in urgent need of it :-). I agree that `AutoPythonAllowThreads` is probably the best place to put it.

Thanks for making the PR

**Comment by andygotz** [comment] 2019-11-29 07:58
I agree with @tiagocoutinho : it sounds logical that it be fixed in the C++ layer

**Comment by bourtemb** [comment] 2019-11-29 18:02
> Tango C++ is supposed to be thread safe. There is no mention to `ensure_self` whatsoever in the Tango C++ documentation, so we don't know which calls to the Tango C++ layer need to be protected with `ensure_self`.

You're right. cppTango was originally developed at a time where C++ didn't have standard threads.
All the threads currently created in cppTango are omni threads, since this is what omniORB is using to create threads and since this implementation is available for free with omniORB.
Users used to create omni threads in the past so there was no issue.
Since C++11, C++ comes with an implementation of standard threads.
cppTango is currently not directly thread safe when a user is using C++11 standard threads or threads different than omni threads.

I think the correct work-around when using threads which are not omni threads is to create an object of the class `omni_thread::ensure_self` in the created thread, just after the thread creation and to delete this object only when the thread has finished its job.

You're right when you say this is not documented. And it is a mistake. The documentation has not been updated with this information since the first issues of this kind have been reported.
The main reason for this is that deeper investigations would be needed to better understand the implications of using `ensure_self `and to ensure we use it the proper way.

> IMHO, Tango C++ should protect itself with `ensure_self` where it needs. Another benefit would be that any other library (ex: qtango) would profit from this improvement.

Going for this solution would avoid some crashes but would probably not give the expected behaviour.
I think the `ensure_self `object has to be there for the whole lifetime of the created thread because this is used in some ReaderWriter locks which can ensure that a thread which has already taken a lock can take it again without blocking (the thread id is used in this case to identify the thread).
There are probably some situations where it is fine to have the `ensure_self `object created just during the invocation of some cppTango methods but I don't know the list of these methods right now. This really needs some investigations and it really depends on what the user is doing in his threads.

Please have a look at this simple example which illustrates the behaviour of the ensure_self and omni_thread::self()->id() method: https://gist.github.com/bourtemb/9ed7337df4ba88d0ddccb4007f22135c

The ReaderWriter locks used internally in cppTango are currently using this omni_thread::self()->id() to identify the thread asking for the lock.

> If not, then I propose the Tango c++ documents which calls need to have this protection so that in PyTango we know what code needs to be changed.

Yes, that would be great. We really need to study in more details the current code to be able to give you such a list.

**Comment by ajoubertza** [comment] 2019-12-02 19:42
Thanks for all the details @bourtemb.  From that it seems my idea of using `ensure_self` in `AutoPythonAllowThreads` is not a safe approach.   That leaves my earlier suggestion:

> Another option is expose ensure_self via Boost, and then to make an a new Python class deriving from threading.Thread that uses it. The downside of this approach is that users have to know they must use this special class for their own threads.

I don't see a nice way to extend `threading.Thread` that would do this and handle the setup and cleanup automatically.  Best we do is provide access to `ensure_self` as a context handler, then we could have code like this:

```python
import tango
from threading import Thread
from time import sleep


def my_thread_func():
    with tango.EnsureOmniThread:
        while running:
            # call things with Tango functions...


thread = Thread(target=my_thread_func)
running = True
thread.start()
sleep(1)
running = False
thread.join()
```

We would still have to warn people to use it in the documentation, and there is a good chance some will not do so.

We could take an extreme approach:  crash if `omni_thread::self` is `null` whenever we use `AutoPythonAllowThreads`.  I like that option - fail loudly.

**Comment by ajoubertza** [comment] 2020-02-19 19:33
I've merged the code with the new context handler, so closing this.

**Closed as completed by ajoubertza** 2020-02-19 19:33 UTC

**Comment by reszelaz** [comment] 2020-02-24 17:51
Just to complement this issue, in the case of the Sardana project I was not able to reproduce the problem when subscribing to events within the device server process - Sardana single device server.
My test was executing two macros (two `threading.Thread`) in parallel on two different Door devices. Each of these macros was constantly subscribing and unsubscribing to events of attributes proceeding from other devices exported within the same device server process.
When I separated the architecture in a single Pool device server and a single MacroServer device server I got the same problem - API_EventTimeout. So, in this case the two macros are running in a different process. Then simply using the `EnsureOmniThread` avoids the problem.

Another observation is that I was not able to reproduce it with Tango 7. I think we will test it on Tango 8 soon.

**Comment by bourtemb** [comment] 2020-05-25 00:50
FYI, the [C++ example](https://github.com/tango-controls/pytango/files/3879504/test_dev_sub.cpp.tar.gz) provided by @tiagocoutinho in a comment above seems to work as expected when using a cppTango version containing the patch provided by tango-controls/cppTango#699 PR.
