### ISSUE TITLE
PyTango mandatory device property with default value

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/pytango#380] opened 2020-09-18 10:38 UTC
https://github.com/tango-controls/pytango/blob/d467c1be41ab0ff888a5a6cd7041a9780ff40468/tango/server.py#L1214

Does not that mean that there is no way to define a mandatory property with a default value, does it?

**Comment by Ingvord** [comment] 2020-09-18 10:41
Removing mandatory requirement does prevent exception, but the default value is not set...

**Comment by bourtemb** [comment] 2020-09-18 11:55
As far as I understood, a mandatory property is a property which shall be defined in the Tango Database so it does not make sense to have a default value for such properties.

**Comment by ajoubertza** [comment] 2020-10-07 20:11
Thanks @bourtemb.  I agree.

@Ingvord Can we close this issue?

**Comment by Ingvord** [comment] 2020-10-08 08:30
Well, the error message is misleading anyway. Should we open another one for that?

**Comment by ajoubertza** [comment] 2020-10-08 10:55
Oh, I see.  We can discuss the misleading message here.

The current message is:
> "device_property arguments mandatory and default_value are incompatible"

How about:
> "Invalid arguments:  if 'mandatory' is True then 'default_value' must be None.  A mandatory property value must be retrieved from the Tango Database so it cannot have a default."

I see another message related to mandatory - is this one OK as is?
https://github.com/tango-controls/pytango/blob/d467c1be41ab0ff888a5a6cd7041a9780ff40468/tango/server.py#L624

**Comment by Ingvord** [comment] 2020-10-09 16:14
Well, taking into account the fact that `default_value` is basically ignored in favor to `mandatory`, I would say:

`mandatory device property (=True) must be defined in the Tango Database. default_value is ignored in this case.`

If there is access to name field of course that can be enhanced using `format`

**Comment by ajoubertza** [comment] 2020-10-11 13:19
@Ingvord OK, I've made a PR with a new message, combining some of your's and some of mine.

I don't want to change the behaviour, so I'm not ignoring the default - still raising the exception, so the developer can fix the error.

The name of the field is not available, because the error happens before completing the assignment to the field.  However, the location of the problem is obvious from the stack trace.  See the example of `my_bad_property` below:

```
tests/test_test_context.py:None (tests/test_test_context.py)
test_test_context.py:18: in <module>
    class Device1(Device):
test_test_context.py:19: in Device1
    my_bad_property = device_property(dtype=int, mandatory=True, default_value=123)
../tango/server.py:1218: in __init__
    raise ValueError(msg)
E   ValueError: Invalid arguments: 'mandatory' is True, so 'default_value' must be None. A mandatory device property value must be defined in the Tango Database so it cannot have a default.

```

**Comment by Ingvord** [comment] 2020-10-12 11:57
@ajoubertza 

> so I'm not ignoring the default - still raising the exception

yeah I meant raising an exception when `default_value` is set effectively ignores it, as, usually, `default_value`s are in use when no other values are provided. 

> OK, I've made a PR with a new message, combining some of your's and some of mine.

Perfect! Thanks!

**Closed as completed** 2020-10-13 14:21 UTC
Labels: bug, question
