### ISSUE TITLE
Windows: DLL load fail with 9.3.2 64bit wheel

### ISSUE THREAD

**Issue by reszelaz** [tango-controls/pytango#355] opened 2020-05-11 13:49 UTC
When trying the latest release on Windows I found the following problem:

```
  Downloading https://files.pythonhosted.org/packages/8c/f9/fcdffed50c2a812dc455260991711e7ef5655a71e98f56c7cab5e115bee8/pytango-9.3.2-cp27-cp27m-win_amd64.whl (3.8MB)
     |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 3.8MB 2.8MB/s

[...]

Successfully installed IPython-5.10.0 PyTango-9.3.2 ...

[...]

C:\Users\Zibi\workspace\sardana>C:\Python27\python.exe
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tango
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\tango\__init__.py", line 83, in <module>
    from ._tango import (
ImportError: DLL load failed: The specified module could not be found.
>>> import PyTango
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\PyTango.py", line 5, in <module>
    import tango
  File "C:\Python27\lib\site-packages\tango\__init__.py", line 83, in <module>
    from ._tango import (
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by ajoubertza** [comment] 2020-05-11 21:03
@NexeyaSGara Could you please have a look at this?  The wheels came from this [AppVeyor build](https://ci.appveyor.com/project/tiagocoutinho/pytango/builds/32567594).

@andygotz Does it work on your version of Windows?

**Comment by reszelaz** [comment] 2020-05-15 15:00
Just to complement this report... It actually was dicovered in [tango-controls.org Forum](https://www.tango-controls.org/community/forum/c/general/installation/sardana-283-build-on-windows-10-problem/?page=1#post-4326). 
I install PyTango with pip (python 2) on a freshly system wide installed python with `pip install PyTango`.

**Comment by ldoyle** [comment] 2020-05-21 14:58
I can confirm this bug on my Windows 10 system running Anaconda3.
It seems to be related to a missing Pthreads DLL.

Steps: Create a new virtual environment with python=2.7
conda install numpy
pip install PyTango
python> import tango -> DLL load failed

Using Visual Studio command line tool I ran `dumpbin /imports _tango.pyd` to confirm the imported DLLs, of which only `pthreadVC2.dll` seemed unusual. Downloading `pthreads-win32-2.9.1_x64-msvc15.zip` from https://github.com/tango-controls/Pthread_WIN32/releases
and pasting both DLLs from `bin/` in the site-packages/tango directory next to `_tango.pyd` solved the `ImportError`.

This is just my home laptop with PyTango but without database installed, so I cannot confirm correct/crash-free real-world behaviour, but I'm confident this should work.

Should the Pthread DLLs normally be deployed in the PyTango wheel or is something else going wrong here?

**Comment by ldoyle** [comment] 2020-05-21 15:05
Same problem and same solution goes for `pip install PyTango` on python 3.7 (will get PyTango 9.3.2),
however in this case I am unsure whether it is wise to copy the DLL from `pthreads-win32-2.9.1_x64-msvc15`, since python shows `MSC v.1916 64 bit`. Is there a more recent version of pthreads or is this difference fine?

PyTango version 9.3.1 from conda-forge for Py3.7,amd64 did not have this dependency and runs fine.

**Comment by ajoubertza** [comment] 2020-05-23 20:52
@ldoyle Thanks for the updates.
The requirement for pythread was only added in 9.3.2.  See commit 017f72b649887.  It also shows which versions of pthread we download for the AppVeyor compilation on different platforms.

If you have any ideas how to fix it, that would be appreciated.  Maybe a change is in needed in [appveyor.yml](https://github.com/tango-controls/pytango/blob/develop/appveyor.yml) or [winsetup.py](https://github.com/tango-controls/pytango/blob/develop/winsetup.py) to include the correct pthread library in the wheel?

**Comment by ldoyle** [comment] 2020-05-26 11:51
Hi Anton,
as you can see in the PR #358 I tried static linking to avoid the DLL altogether, but this fails for various reasons and I am not proficient enough in the static/dynamic link area to fix this. Instead, as mentioned, it would probably be easier to copy the DLL to the wheel/ package destination by minor changes to `setup.py` and `appveyor.yml`.

Once the DLL is copied by AppVeyor to the build target directory (from which the wheel is formed), it should be enough to add `*.dll` or `pthreadVC2.dll` to `package_data` in `setup.py` (keeping in mind the DLL is not necessary/available on linux, so caution in `setup.py`, and maybe a workaround in `winsetup.py` is better).

Maybe I get round to testing it until the end of the week if no one else is faster.

**Comment by andygotz** [comment] 2020-06-11 13:42
Hi @piogor , 
I have assigned this to you as the first task for the PyTango support. Can you assign this to the right person? I hope s/he knows Windows 8-). 
You can ask @ajoubertza for technical details about this issue. 
Thanks in advance!

**Comment by ldoyle** [comment] 2020-06-11 15:30
I added some comments about what I think might be going wrong in my (so far failing) PR #358. Should this information rather be moved here in case my PR gets closed/cancelled?

**Comment by ajoubertza** [comment] 2020-06-12 04:58
> Should this information rather be moved here in case my PR gets closed/cancelled?

No, in the PR is fine.  Even if we close it, the history will remain in Github.

**Comment by wkitka** [comment] 2020-06-15 07:12
Hi @ajoubertza  ,
I investigate it.

**Comment by wkitka** [comment] 2020-06-19 14:22
Hi @ajoubertza ,
I added pthread .dll files in #367

**Comment by spirit1317** [comment] 2020-11-17 10:11
Hello,

I started working on this ticket, continuing from ba65e3899227c149175a1089b8bfb2278a0b9131. I discovered two additional problems with pytango 9.3.2 on Winows:

problem 1:
```python
import tango
db = tango.Database()
```

If TANGO_HOST is not set, on tango 9.3.1 it throws exception, but on 9.3.2 python ends abruptly without any warning.

problem 2:
```python
from tango.server import Device
from tango.test_utils import DeviceTestContext

with DeviceTestContext(Device) as event_device:
    print("will not get printed")
```

It crases without any error in `__DeviceClass__device_factory` in `device_class.py` calling `self.export_device`.

Both problems seem to come from _tango extension. Is anybody also getting those?

I started looking for a solution from https://github.com/tango-controls/pytango/pull/358#issuecomment-642736233 and heres what I got:

- @ldoyle is writing that CppTango 9.3.3 is using Pthreads-win32, but in fact it's probably some leftover in appveyor.yml, because I couldn't see it used anywhere in the code. CppTango is using OmniThreads for all threads (pooling, heartbeat, worker threads). @mliszcz helped with this insight

- OmniOrb is using <pthreads.h> on Linux and NT Threads on Windows. It is controlled by preprocessor macro: `__WIN32__`  in `omniorb.h`. Although Visual Studio is defining `_WIN32`, not `__WIN32__` those are defined in omniorb make files so it gets builded properly.

- In CppTango cmake_win_defs.cmake there is _WIN32 macro defined, but I could not find `__WIN32__` anywhere, so in the next step I will `add_definitions(-D__WIN32__)`

- Many times tracing the problem leads to `_tango` boost [extension](https://docs.python.org/3/extending/extending.html), which exposes CppTango as `_tango.pyd`. Unfortunately it's hard to read this code. @ajoubertza asked the creators of this extension to provide some documentation.

**Comment by spirit1317** [comment] 2020-12-03 07:40
Hi,

I think I might find the solution.

- Like mentioned in my prievious comment, `<omnithread.h> `needs `__WIN32__` macro to be defined on windows.

- Normally when using CppTango, `__WIN32__` macro is defined inside `tango_conf.h` (imported from `<tango.h>`), but in PyTango Boost extension we have file `ext/pyutils.py` importing `<omnithread.h>` without importing `<tango.h>`

- Error described [here](https://github.com/tango-controls/pytango/pull/327#issuecomment-576824090) was caused because in `ext/dev_error.cpp` the import of `<tango.h>` [was](https://github.com/tango-controls/pytango/blob/a04dcbc4d6eb65b5f038ea289840217e7c87cb7a/ext/dev_error.cpp#L13) accidentally put after `pyutils.py` import. Without `__WIN32__` macro, omnithred was looking for `omnithread/posix.h` which includes `pthread.h`. Suggested answer to add  `__POSIX_NT__` to CMakeLists.txt was incorrect, because this flag is for Cygwin compilation on windows.

- If `__WIN32__` macro is defined, Pthreads-32 seems not needed for PyTango compilation

Solution 1:
We can rememer to include <tango.h> in all Boost extension files even if we will not use it, just to have `__WIN32__` macro defined. Like in this commit: 22563dc6bf731df1ef3978ade0f3b4e9403da9bb

Solution 2:
We can `add_definitions(-D__WIN32__)` to CMakeLists.txt like here, but it will cause later `macro redefinition` error.

@ajoubertza Could you please check if everything is alright and the ticket can be closed?

**Comment by ajoubertza** [comment] 2020-12-03 09:29
Nice work, @spirit1317.  That is some good debugging!

I think solution 1 is the better option.  Although, we do not need to add `<tango.h>` to any extension files.  Files that already have it keep (fixing the include order).  Files that don't have it, don't need it.  If we make a mistake with the order in future, the Windows compilation will fail again because of the missing `pthread.h` (then we must just remember not to add pthread!).

We can only close this ticket once there is a solution merged into the develop branch, and we have confirmed it is working.  Please make a pull request with your fixes for the Windows issues, as above.  After that, you can make another pull request to enable the test suite in CI under Windows (I will comment more on that ticket).

**Comment by spirit1317** [comment] 2020-12-03 09:50
Hi, thanks for your reply,

_`Although, we do not need to add <tango.h> to any extension files.`_

When I tried compiling PyTango without added `tango.h` import to `pyutils.h` it complained, so I think it might be required to add it.

**Comment by ajoubertza** [comment] 2020-12-03 11:48
> When I tried compiling PyTango without added `tango.h` import to `pyutils.h` it complained, so I think it might be required to add it.

Sorry, I wasn't clear in my comment.  I'm sure the file is important, and the extension files that already include it must continue to do so.  So yes, `pyutils.h` must still include `tango.h`.

**Comment by birkenfeld** [comment] 2020-12-03 14:30
Please only close this once a fixed version is posted to pypi. The current state is quite bad, with pip installing the broken package.

**Comment by ajoubertza** [comment] 2020-12-14 20:24
Re-opening, as new release still has to be made.

**Comment by ajoubertza** [comment] 2021-01-07 19:45
A new release, 9.3.3, is available on [PyPI](https://pypi.org/project/pytango/9.3.3/) and should work with Windows now.  Closing this issue.  If there are any problems with the new version, please create a new issue.

**Closed as completed by ajoubertza** 2021-01-07 19:45 UTC
