### ISSUE TITLE
WARNING: Block quote ends without a blank line

### ISSUE THREAD

**Issue by picca** [tango-controls/pytango#207] opened 2018-08-01 08:03 UTC
Hello,

just a minor bug :)

/<<PKGBUILDDIR>>/doc/data_types.rst:57: WARNING: Block quote ends without a blank line; unexpected unindent.
looking for now-outdated files... none found

**Comment by picca** [comment] 2018-08-01 08:03
another one

/<<PKGBUILDDIR>>/doc/tep/tep-0002.rst:66: WARNING: undefined label: persistence (if the link has no caption the label must precede a section header)

**Comment by vxgmichel** [comment] 2018-08-01 11:30
Thanks for the report! 

I haven't been able to reproduce the second warning though, anything special about your setup?

**Comment by picca** [comment] 2018-08-01 11:38
here the build log

https://buildd.debian.org/status/fetch.php?pkg=pytango&arch=amd64&ver=9.2.4-2&stamp=1533071833&raw=0

**Comment by vxgmichel** [comment] 2018-08-01 11:53
Somehow, this warning is due to the absence of network connection. I'm not sure there is anything to fix here.

**Comment by picca** [comment] 2018-08-01 11:54
What is strange is that I do not have this message for python3.6 and python2.7

**Comment by vxgmichel** [comment] 2018-08-01 11:57
Weird. Anyway, I don't get anymore warnings building the docs. Can we close this isssue?

**Closed as completed** 2018-08-01 11:57 UTC
