### ISSUE TITLE
Emit push_change_event with a custom time stamp

### ISSUE THREAD

**Issue by cmft** [tango-controls/pytango#155] opened 2017-08-25 15:00 UTC
Dear community,
I'm trying to do tests and I need to send a push_change_event with a custom time stamp.
I tried to do it with a dummy ds, via a command (see the attached code) the command sent the push change event but it did not send the given time stamp.

Is it possible?

```
import time
import PyTango
from PyTango.server import (run, 
                            Device,
                            DeviceMeta, 
                            attribute, 
                            command)


class DummyPushEvent(Device):
    __metaclass__ = DeviceMeta
    
    def init_device(self):
        Device.init_device(self)
        self._value = 999
        self.set_change_event('value',True,False)

    @attribute(label="value", dtype=int)
    def value(self):
        return self._value

    @value.write
    def value(self, value):
        self._value = value
        self.push_change_event('value', value)

        
    @command(dtype_in=[float,])
    def PushEvent(self, data):
        self.info_stream('Run PushEvent')
        if len(data) == 1:
            ts = time.time()
        else:
            ts = data[1]
        # push_change_event (self, attr_name, data, time_stamp, quality,
        #                    dim_x = 1, dim_y = 0)
        self.push_change_event('value', data[0], ts, 
                               PyTango.AttrQuality.ATTR_VALID, 1, 0)


if __name__ == "__main__":
    run((DummyPushEvent,))
``` 

Test:
```
import PyTango
d = PyTango.DeviceProxy('dummy/test/1')
d.subscribe_event('value', PyTango.EventType.CHANGE_EVENT, PyTango.utils.EventCallBack())
d.PushEvent([5, 1503670542.188912]) # time stamp should be 2017-8-25 16:15:42
2017-08-25 16:54:05.452937 DUMMY/TEST/1 VALUE CHANGE [ATTR_VALID] 5

``` 

Best Carlos

PD: I'm using Tango 9.2.5 and PyTango 9.2.1

**Comment by vxgmichel** [comment] 2017-08-28 11:28
Hi @cmft,

Thank you for your report, I'm investigating this issue.

**Comment by vxgmichel** [comment] 2017-08-28 14:21
It turns out that `tango.utils.EventCallBack` uses `event.get_date()` which returns the reception date. IMO this is NOT the expected behavior and I think it should be fixed. In the meantime, you can access the timestamp using:

 - `event.attr_value.time.totime()`
 - `event.attr_value.time.todatetime()`

**Comment by cmft** [comment] 2017-08-28 14:23
Thanks @vxgmichel!!

**Closed as completed** 2017-09-07 12:19 UTC
